=== DataONEorg/d1_cn_common/src/main/resources/org/dataone/service/resources/schema/listobjects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://dataone.org/service/types/ListObjects/0.1"
    version="0.1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://dataone.org/service/types/ListObjects/0.1"
    xmlns:common="http://dataone.org/service/types/common/0.1"
    elementFormDefault="unqualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="http://dataone.org/service/types/common/0.1" 
        schemaLocation="file:///home/rwaltz/Projects/NetBeans/DataONE-ServiceAPI/src/main/resources/org/dataone/service/resources/schema/common.xsd" />
     <xs:complexType name="ObjectInfo">
        <xs:sequence>
            <xs:element name="identifier"  type="common:Identifier" minOccurs="1" maxOccurs="1"/>
            <xs:element name="objectFormat" type="common:ObjectFormat"/>
            <xs:element name="checksum" type="common:Checksum"
                    minOccurs="1" maxOccurs="1" />
            <xs:element name="dateSysMetadataModified" type="xs:dateTime"/>
            <xs:element name="size" type="xs:long"/>

        </xs:sequence>
<!--        <xs:attribute name="identifier" use="required" type="common:Identifier"/> -->
    </xs:complexType>

  <xs:complexType name="ListObjects">
      
       <xs:sequence>
        <xs:element name="objectInfo" type="ObjectInfo"
                    minOccurs="0" maxOccurs="unbounded" />
       </xs:sequence>
      <xs:attribute name="count" use="required" type="xs:int"/>
      <xs:attribute name="start" use="required" type="xs:int"/>
      <xs:attribute name="total" use="required" type="xs:int"/>

  </xs:complexType>

  <xs:element name="listObjects" type="ListObjects" />
</xs:schema>

=== DataONEorg/d1_cn_common/src/test/resources/org/dataone/service/samples/listObjectsSample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<d1:listObjects xmlns:d1="http://dataone.org/service/types/ListObjects/0.1"
 xmlns:common="http://dataone.org/service/types/common/0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dataone.org/service/types/ListObjects/0.1 file:/home/rwaltz/Projects/NetBeans/DataONE-CnPrototype/DataONE-CnDomain/src/main/resources/org/dataone/service/resources/schema/listobjects.xsd" 
 count="2" start="0" total="2">
    <objectInfo>
        <identifier>ABC123</identifier>
        <objectFormat>eml://ecoinformatics.org/eml-2.0.0</objectFormat>
        <checksum algorithm="SHA-1">SGVsbG8gV29ybGQh</checksum>
        <dateSysMetadataModified>2006-05-04T18:13:51.0Z</dateSysMetadataModified>
        <size>922337203</size>
    </objectInfo>
    <objectInfo>
        <identifier>ABC456</identifier>
        <objectFormat>eml://ecoinformatics.org/eml-2.0.0</objectFormat>
        <checksum algorithm="SHA-1">V29ybGQgSGVsbG8h</checksum>
        <dateSysMetadataModified>2006-05-05T18:13:51.0Z</dateSysMetadataModified>
        <size>922337203</size>
    </objectInfo>
</d1:listObjects>
