=== DataONEorg/d1_cn_common/src/main/resources/org/dataone/service/resources/schema/logging.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://dataone.org/service/types/logging/0.1"
    version="0.1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:common="http://dataone.org/service/types/common/0.1"
    targetNamespace="http://dataone.org/service/types/logging/0.1"
    elementFormDefault="unqualified" attributeFormDefault="unqualified">
    <xs:import namespace="http://dataone.org/service/types/common/0.1"
        schemaLocation="file:///home/rwaltz/Projects/NetBeans/DataONE-ServiceAPI/src/main/resources/org/dataone/service/resources/schema/common.xsd" />
    
    <!-- TODO: Discuss the namespace for this document, and pick an effective, versioned URI for the namespace -->

    <xs:simpleType name="Event">
        <xs:restriction base="xs:string">
            <xs:enumeration value="create"/>
            <xs:enumeration value="read"/>
            <xs:enumeration value="update"/>
            <xs:enumeration value="delete"/>
            <xs:enumeration value="replicate"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="LogEntry">
        <xs:sequence>
            <xs:element name="entryId" type="common:Identifier" 
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="identifier" type="common:Identifier" 
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="ipAddress" type="xs:string"
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="userAgent" type="xs:string"
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="principal" type="common:Principal"
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="event" type="Event"
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="dateLogged" type="xs:dateTime"
                minOccurs="1" maxOccurs="1"/>
            <xs:element name="memberNode" type="common:NodeReference"
                minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of the Logging element -->
    <xs:element name="log">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="logEntry" type="LogEntry"
                    minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== DataONEorg/d1_cn_common/src/test/resources/org/dataone/service/samples/loggingSample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<d1:log xmlns:common="http://dataone.org/service/types/common/0.1"
 xmlns:d1="http://dataone.org/service/types/logging/0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dataone.org/service/types/logging/0.1 https://repository.dataone.org/software/cicore/trunk/schemas/logging.xsd">
    <logEntry>
        <entryId>123</entryId>
        <identifier>ABC</identifier>
        <ipAddress>1.2.3.4</ipAddress>
        <userAgent>userAgent0</userAgent>
        <principal>me</principal>
        <event>create</event>
        <dateLogged>2006-05-04T18:13:51.0Z</dateLogged>
        <memberNode>mn1</memberNode>
    </logEntry>
    <logEntry>
        <entryId>456</entryId>
        <identifier>DEF</identifier>
        <ipAddress>0.1.0.2</ipAddress>
        <userAgent>userAgent1</userAgent>
        <principal>you</principal>
        <event>create</event>
        <dateLogged>2006-05-04T18:13:51.0Z</dateLogged>
        <memberNode>mn1</memberNode>
    </logEntry>
    <logEntry>
        <entryId>789</entryId>
        <identifier>GHI</identifier>
        <ipAddress>5.4.3.2</ipAddress>
        <userAgent>userAgent2</userAgent>
        <principal>it</principal>
        <event>create</event>
        <dateLogged>2006-05-04T18:13:51.0Z</dateLogged>
        <memberNode>mn1</memberNode>
    </logEntry>
</d1:log>
