=== DataONEorg/d1_cn_common/src/main/resources/org/dataone/service/resources/schema/systemmetadata.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://dataone.org/service/types/SystemMetadata/0.1"
    version="0.1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:common="http://dataone.org/service/types/common/0.1"
    targetNamespace="http://dataone.org/service/types/SystemMetadata/0.1"
    elementFormDefault="unqualified" attributeFormDefault="unqualified">
    <xs:import namespace="http://dataone.org/service/types/common/0.1" 
        schemaLocation="file:///home/rwaltz/Projects/NetBeans/DataONE-ServiceAPI/src/main/resources/org/dataone/service/resources/schema/common.xsd" />
    
    <!-- TODO: Discuss the namespace for this document, and pick an effective, versioned URI for the namespace -->

    <xs:complexType name="AccessRule">
        <xs:attribute name="rule">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="allow"/>
                    <xs:enumeration value="deny"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>

        <xs:attribute name="service">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="read"/>
                    <xs:enumeration value="write"/>
                    <xs:enumeration value="changePermission"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>

        <xs:attribute name="principal" type="common:Principal"/>
    </xs:complexType>

    <xs:complexType name="ReplicationPolicy">
        <xs:sequence>
            <xs:element name="preferredMemberNode" type="common:NodeReference"
                minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="blockedMemberNode" type="common:NodeReference"
                minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>

        <xs:attribute name="replicationAllowed">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>

        <xs:attribute name="numberReplicas" type="xs:int"/>
    </xs:complexType>

    <!-- Definition of the SystemMetdata element -->
        <xs:complexType name="SystemMetadata">
            <xs:sequence>
                <!-- Client Provided system metadata fields -->
                <xs:element name="identifier" type="common:Identifier" minOccurs="1" maxOccurs="1"/>
                <xs:element name="objectFormat" type="common:ObjectFormat"/>
                <xs:element name="size" type="xs:long"/>
                <xs:element name="submitter" type="common:Principal"/>
                <xs:element name="rightsHolder" type="common:Principal"/>

                <!-- Client provided relationship fields -->
                <xs:element name="obsoletes" type="common:Identifier" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element name="obsoletedBy" type="common:Identifier" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element name="derivedFrom" type="common:Identifier" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element name="describes" type="common:Identifier" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element name="describedBy" type="common:Identifier" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element name="checksum" type="common:Checksum"
                    minOccurs="1" maxOccurs="1" />
                <xs:element name="embargoExpires" type="xs:dateTime"
                    minOccurs="0"/>
                <xs:element name="accessRule" type="AccessRule"
                    minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="replicationPolicy" type="ReplicationPolicy"
                    minOccurs="0" maxOccurs="1" />

                <!-- Fields provided by Member Node and Coordinating Node -->
                <xs:element name="dateUploaded" type="xs:dateTime"/>
                <xs:element name="dateSysMetadataModified" type="xs:dateTime"/>

                <xs:element name="originMemberNode" type="common:NodeReference"/>
                <xs:element name="authoritativeMemberNode" type="common:NodeReference"/>
                <xs:element name="replica" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="replicaMemberNode" type="common:NodeReference"/>
                            <xs:element name="replicationStatus">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="queued"/>
                                        <xs:enumeration value="requested"/>
                                        <xs:enumeration value="completed"/>
                                        <xs:enumeration value="invalidated"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="replicaVerified" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    
    <xs:element name="systemMetadata" type="SystemMetadata"></xs:element>

</xs:schema>

=== DataONEorg/d1_cn_common/src/test/resources/org/dataone/service/samples/systemMetadataSample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    This work was created by participants in the DataONE project, and is
    jointly copyrighted by participating institutions in DataONE. For
    more information on DataONE, see our web site at http://dataone.org.

      Copyright ${year}

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<d1:systemMetadata xmlns:common="http://dataone.org/service/types/common/0.1"
 xmlns:d1="http://dataone.org/service/types/SystemMetadata/0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dataone.org/service/types/SystemMetadata/0.1 https://repository.dataone.org/software/cicore/tags/D1_SCHEMA_0_4/systemmetadata.xsd">
    <identifier>ABC123</identifier>
    <objectFormat>eml://ecoinformatics.org/eml-2.0.0</objectFormat>
    <size>922337203</size>
    <submitter>Robert P Waltz</submitter>
    <rightsHolder>DataONE</rightsHolder>
    <obsoletes>AFC123</obsoletes>
    <obsoletedBy>AFC12352</obsoletedBy>
    <derivedFrom>AFC</derivedFrom>
    <describes>AFC</describes>
    <describedBy>CFA</describedBy>
    <checksum algorithm="SHA-1">SGVsbG8gV29ybGQh</checksum>
    <embargoExpires>2006-05-04T18:13:51.0Z</embargoExpires>
    <accessRule rule="allow" service="read" principal="mn1 "/>
    <replicationPolicy replicationAllowed="true" numberReplicas="2147483647">
        <preferredMemberNode>mn1</preferredMemberNode>
        <blockedMemberNode>mn2</blockedMemberNode>
    </replicationPolicy>
    <dateUploaded>2006-05-04T18:13:51.0Z</dateUploaded>
    <dateSysMetadataModified>2006-05-04T18:13:51.0Z</dateSysMetadataModified>
    <originMemberNode>mn1</originMemberNode>
    <authoritativeMemberNode>mn1</authoritativeMemberNode>
    <replica>
        <replicaMemberNode>mn3</replicaMemberNode>
        <replicationStatus>queued</replicationStatus>
        <replicaVerified>2006-05-04T18:13:51.0Z</replicaVerified>
    </replica>
</d1:systemMetadata>
